### ISSUE TITLE
Publish package on Packagist

### ISSUE THREAD

**Issue by saidimu** [glopgar/monolog-timer-processor#1]
Please publish your package on https://packagist.org/.

This will make it easier to discover and install.

Thanks!

**Comment by mattmeye** [comment]
or/and composer. see http://stackoverflow.com/questions/12954051/use-php-composer-to-clone-git-repo/14485706#14485706

**Comment by spotman** [comment]
:+1:

**Comment by glopgar** [comment]
I've published the package in Packagist:

https://packagist.org/packages/glopgar/monolog-timer-processor
